2024-04-17T00:00:01 {"cpu": 0.0, "cpu_total": 8, "cpu_usage": 0.0, "memory": 1542.0, "memory_total": 4954.0, "memory_usage": 0.3112636253532499, "pipeline_run_id": 10, "pipeline_schedule_id": 4, "pipeline_uuid": "reddit_pipeline", "hostname": "df052f968d95", "level": "INFO", "message": "Pipeline reddit_pipeline for run 10 in schedule 4 is alive.", "timestamp": 1713312001.947827, "uuid": "5918a432f2644e22af41c697306504b9"}
2024-04-17T00:00:02 {"cpu": 0.0, "cpu_total": 8, "cpu_usage": 0.0, "memory": 1549.0, "memory_total": 4954.0, "memory_usage": 0.31267662494953574, "pipeline_run_id": 10, "pipeline_schedule_id": 4, "pipeline_uuid": "reddit_pipeline", "hostname": "df052f968d95", "level": "INFO", "message": "Pipeline reddit_pipeline for run 10 in schedule 4 is alive.", "timestamp": 1713312002.185001, "uuid": "6315e74b68814bb5a71bd158990e7235"}
2024-04-17T00:00:02 {"block_run_id": 49, "block_uuid": "load_reddit", "pipeline_run_id": 10, "pipeline_schedule_id": 4, "pipeline_uuid": "reddit_pipeline", "hostname": "df052f968d95", "level": "INFO", "message": "Execute PipelineRun 10, BlockRun 49: pipeline reddit_pipeline block load_reddit", "timestamp": 1713312002.865151, "uuid": "3394ef4e95e74a33a38d6826d777e9ed"}
2024-04-17T00:00:10 {"cpu": 0.0, "cpu_total": 8, "cpu_usage": 0.0, "memory": 1536.0, "memory_total": 4954.0, "memory_usage": 0.31005248284214776, "pipeline_run_id": 10, "pipeline_schedule_id": 4, "pipeline_uuid": "reddit_pipeline", "hostname": "df052f968d95", "level": "INFO", "message": "Pipeline reddit_pipeline for run 10 in schedule 4 is alive.", "timestamp": 1713312010.62943, "uuid": "b4ef734cb0324c6e97b772d6b7c2c3c2"}
2024-04-17T00:00:16 {"block_run_id": 49, "block_uuid": "load_reddit", "pipeline_run_id": 10, "pipeline_schedule_id": 4, "pipeline_uuid": "reddit_pipeline", "hostname": "df052f968d95", "level": "INFO", "message": "BlockRun 49 (block_uuid: load_reddit) completes.", "timestamp": 1713312016.499699, "uuid": "72110496b10645bf96d823123bb7895a"}
2024-04-17T00:00:21 {"cpu": 0.0322265625, "cpu_total": 8, "cpu_usage": 0.0040283203125, "memory": 2085.0, "memory_total": 4954.0, "memory_usage": 0.42087202260799356, "pipeline_run_id": 10, "pipeline_schedule_id": 4, "pipeline_uuid": "reddit_pipeline", "hostname": "df052f968d95", "level": "INFO", "message": "Pipeline reddit_pipeline for run 10 in schedule 4 is alive.", "timestamp": 1713312021.020355, "uuid": "6c4b2f46643c48e1887c143e34518e5f"}
2024-04-17T00:00:22 {"block_run_id": 50, "block_uuid": "transform_reddit", "pipeline_run_id": 10, "pipeline_schedule_id": 4, "pipeline_uuid": "reddit_pipeline", "hostname": "df052f968d95", "level": "INFO", "message": "Execute PipelineRun 10, BlockRun 50: pipeline reddit_pipeline block transform_reddit", "timestamp": 1713312022.076209, "uuid": "be4a6bfb70c841e9a4ab9c591cf99caa"}
2024-04-17T00:00:31 {"cpu": 0.1826171875, "cpu_total": 8, "cpu_usage": 0.0228271484375, "memory": 2874.0, "memory_total": 4954.0, "memory_usage": 0.5801372628179249, "pipeline_run_id": 10, "pipeline_schedule_id": 4, "pipeline_uuid": "reddit_pipeline", "hostname": "df052f968d95", "level": "INFO", "message": "Pipeline reddit_pipeline for run 10 in schedule 4 is alive.", "timestamp": 1713312031.45395, "uuid": "f38f836f77c242a7a2a91318e79e86ad"}
2024-04-17T00:00:41 {"cpu": 0.3359375, "cpu_total": 8, "cpu_usage": 0.0419921875, "memory": 2592.0, "memory_total": 4954.0, "memory_usage": 0.5232135647961244, "pipeline_run_id": 10, "pipeline_schedule_id": 4, "pipeline_uuid": "reddit_pipeline", "hostname": "df052f968d95", "level": "INFO", "message": "Pipeline reddit_pipeline for run 10 in schedule 4 is alive.", "timestamp": 1713312041.565648, "uuid": "a3e29e9284184bc3843acf49069b63ac"}
2024-04-17T00:00:51 {"cpu": 0.41845703125, "cpu_total": 8, "cpu_usage": 0.05230712890625, "memory": 2098.0, "memory_total": 4954.0, "memory_usage": 0.4234961647153815, "pipeline_run_id": 10, "pipeline_schedule_id": 4, "pipeline_uuid": "reddit_pipeline", "hostname": "df052f968d95", "level": "INFO", "message": "Pipeline reddit_pipeline for run 10 in schedule 4 is alive.", "timestamp": 1713312051.192011, "uuid": "1faf9d2f03dd4e6c8c9909980165092f"}
2024-04-17T00:00:58 {"block_run_id": 50, "block_uuid": "transform_reddit", "pipeline_run_id": 10, "pipeline_schedule_id": 4, "pipeline_uuid": "reddit_pipeline", "hostname": "df052f968d95", "level": "INFO", "message": "BlockRun 50 (block_uuid: transform_reddit) completes.", "timestamp": 1713312058.824087, "uuid": "d98710aa357d4eebad547c0d153fdc8d"}
2024-04-17T00:01:02 {"cpu": 0.45751953125, "cpu_total": 8, "cpu_usage": 0.05718994140625, "memory": 1462.0, "memory_total": 4954.0, "memory_usage": 0.2951150585385547, "pipeline_run_id": 10, "pipeline_schedule_id": 4, "pipeline_uuid": "reddit_pipeline", "hostname": "df052f968d95", "level": "INFO", "message": "Pipeline reddit_pipeline for run 10 in schedule 4 is alive.", "timestamp": 1713312062.352036, "uuid": "906c3fdb833b4e1080b08ceb4110b3e3"}
2024-04-17T00:01:04 {"block_run_id": 51, "block_uuid": "export_reddit", "pipeline_run_id": 10, "pipeline_schedule_id": 4, "pipeline_uuid": "reddit_pipeline", "hostname": "df052f968d95", "level": "INFO", "message": "Execute PipelineRun 10, BlockRun 51: pipeline reddit_pipeline block export_reddit", "timestamp": 1713312064.152223, "uuid": "b47c8c690eae4169883f4474e98ca1f7"}
2024-04-17T00:01:10 {"block_run_id": 51, "block_uuid": "export_reddit", "pipeline_run_id": 10, "pipeline_schedule_id": 4, "pipeline_uuid": "reddit_pipeline", "hostname": "df052f968d95", "level": "EXCEPTION", "message": "BlockRun 51 (block_uuid: export_reddit) failed.", "timestamp": 1713312070.311764, "uuid": "0894af5d35084116a88b7ae874fe7280", "error": ["Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 613, in execute\n    result = __execute_with_retry()\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 54, in retry_func\n    raise e\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 38, in retry_func\n    return func(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 588, in __execute_with_retry\n    return self._execute(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 1077, in _execute\n    result = self.block.execute_sync(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1258, in execute_sync\n    raise err\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1167, in execute_sync\n    output = self.execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1473, in execute_block\n    outputs = self._execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1629, in _execute_block\n    outputs = self.execute_block_function(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1668, in execute_block_function\n    output = block_function_updated(*input_vars, **global_vars)\n  File \"<string>\", line 23, in export_data_to_big_query\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/io/bigquery.py\", line 552, in with_config\n    return cls(**kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/io/bigquery.py\", line 74, in __init__\n    credentials = service_account.Credentials.from_service_account_file(\n  File \"/usr/local/lib/python3.10/site-packages/google/oauth2/service_account.py\", line 258, in from_service_account_file\n    info, signer = _service_account_info.from_filename(\n  File \"/usr/local/lib/python3.10/site-packages/google/auth/_service_account_info.py\", line 78, in from_filename\n    with io.open(filename, \"r\", encoding=\"utf-8\") as json_file:\nFileNotFoundError: [Errno 2] No such file or directory: '/home/src/secrets/secret.json'\n"], "error_stack": [["  File \"/usr/local/bin/mage\", line 8, in <module>\n    sys.exit(app())\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 311, in __call__\n    return get_command(self)(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1130, in __call__\n    return self.main(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 778, in main\n    return _main(\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 216, in _main\n    rv = self.invoke(ctx)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1657, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1404, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 760, in invoke\n    return __callback(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 683, in wrapper\n    return callback(**use_params)  # type: ignore\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/cli/main.py\", line 163, in start\n    start_server(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/server.py\", line 750, in start_server\n    scheduler_manager.start_scheduler()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 92, in start_scheduler\n    proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 53, in run_scheduler\n    LoopTimeTrigger().start()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/loop_time_trigger.py\", line 14, in start\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/time_trigger.py\", line 11, in run\n    schedule_all()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1654, in schedule_all\n    PipelineScheduler(r).schedule()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 157, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 318, in schedule\n    self.__schedule_blocks(block_runs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 611, in __schedule_blocks\n    job_manager.add_job(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/job_manager.py\", line 28, in add_job\n    self.queue.enqueue(job_id, target, *args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 121, in enqueue\n    self.start_worker_pool()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 198, in start_worker_pool\n    self.worker_pool_proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 351, in poll_job_and_execute\n    worker.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/newrelic/api/background_task.py\", line 117, in wrapper\n    return wrapped(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 315, in run\n    start_session_and_run(args[1], *args[2], **args[3])\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1163, in run_block\n    return ExecutorFactory.get_block_executor(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 641, in execute\n    on_failure(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 157, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 442, in on_block_failure\n    self.logger.exception(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 30, in exception\n    self.__send_message('exception', message, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 65, in __send_message\n    data['error_stack'] = traceback.format_stack(),\n"]], "error_stacktrace": ["[Errno 2] No such file or directory: '/home/src/secrets/secret.json'"]}
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 613, in execute
    result = __execute_with_retry()
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 54, in retry_func
    raise e
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 38, in retry_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 588, in __execute_with_retry
    return self._execute(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 1077, in _execute
    result = self.block.execute_sync(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1258, in execute_sync
    raise err
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1167, in execute_sync
    output = self.execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1473, in execute_block
    outputs = self._execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1629, in _execute_block
    outputs = self.execute_block_function(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1668, in execute_block_function
    output = block_function_updated(*input_vars, **global_vars)
  File "<string>", line 23, in export_data_to_big_query
  File "/usr/local/lib/python3.10/site-packages/mage_ai/io/bigquery.py", line 552, in with_config
    return cls(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/mage_ai/io/bigquery.py", line 74, in __init__
    credentials = service_account.Credentials.from_service_account_file(
  File "/usr/local/lib/python3.10/site-packages/google/oauth2/service_account.py", line 258, in from_service_account_file
    info, signer = _service_account_info.from_filename(
  File "/usr/local/lib/python3.10/site-packages/google/auth/_service_account_info.py", line 78, in from_filename
    with io.open(filename, "r", encoding="utf-8") as json_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/src/secrets/secret.json'
2024-04-17T00:01:11 {"cpu": 0.46337890625, "cpu_total": 8, "cpu_usage": 0.05792236328125, "memory": 1467.0, "memory_total": 4954.0, "memory_usage": 0.2961243439644732, "pipeline_run_id": 10, "pipeline_schedule_id": 4, "pipeline_uuid": "reddit_pipeline", "hostname": "df052f968d95", "level": "INFO", "message": "Pipeline reddit_pipeline for run 10 in schedule 4 is alive.", "timestamp": 1713312071.845574, "uuid": "7fd577d5491549be8ed92a8c8d3cb01a"}
